### ISSUE TITLE
Upgrade to v8 sync api

### ISSUE THREAD

**Issue by garyking** [h6y3/todoist-ruby#7]
Per the docs. [v7 items](https://developer.todoist.com/sync/v7/#items) vs [v8 items](https://developer.todoist.com/sync/v8/#items). One of the changes I noticed, which affected my workflow.

**Comment by h6y3** [comment]
@garyking I was wondering if you ever got the gem to even build.  Were you able to make the change and get it to work?  Strangely, I can't even get the specs to run under ruby 2.6.1

**Comment by garyking** [comment]
I never attempted it. I'm currently using version `0.2.3` of this gem. My long-term plan is to move away from Ruby to TypeScript, so I'm not as familiar with Ruby, building gems, etc. as I used to be.

**Comment by h6y3** [comment]
I was able to get the code to work, turns out that there seems to have been a change in how files are read that always add a \n to the newline and screw up the token for the tests.  Which is great, except now that I've run the tests, I am noticing a bunch of issues like the on your pointed out with the move to the v8 endpoint.  

I'll need to re-run and fix all the issues but hopefully the specs should cover it and I just need to pound through all the use cases.
